apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: openshift-gitops-subscription
  namespace: openshift-gitops
  labels:
    app: argocd
    app.kubernetes.io/part-of: argocd
    apps.open-cluster-management.io/reconcile-rate: high
  annotations:
    apps.open-cluster-management.io/deployables: 
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-current-commit: 
    apps.open-cluster-management.io/git-path: gitops-manifest/operator
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: ns-channel-ocpgitops/channel-openshift-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: openshift-gitops-placementrule
