apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-placementrule-prod
  namespace: openshift-gitops
  labels:
    acm-app: argocd-prod
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      argocd-prod: "True"
