apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-gitops-placementbinding-stage
placementRef:
  name: openshift-gitops-placementrule-stage
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: openshift-gitops-installed-stage
    kind: Policy
    apiGroup: policy.open-cluster-management.io
